#!/usr/bin/env python3
"""
FIND EVIL — PDF Report Generator
Extended from Protocol SIFT's original generate_pdf_report.py.
Adds: iteration trace, accuracy scorecard, discrepancy log.

Usage:
  python3 generate_pdf_report.py \
    --case /cases/CASE01 \
    --findings analysis/findings.json \
    --accuracy reports/accuracy_report.json \
    --output reports/incident_report.pdf
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from weasyprint import HTML
except ImportError:
    print("[ERROR] WeasyPrint not installed. Run: pip3 install weasyprint", file=sys.stderr)
    sys.exit(1)


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>FIND EVIL — Incident Report</title>
<style>
  body {{ font-family: 'Courier New', monospace; margin: 40px; color: #1a1a1a; }}
  h1 {{ color: #c0392b; border-bottom: 3px solid #c0392b; padding-bottom: 8px; }}
  h2 {{ color: #2c3e50; border-bottom: 1px solid #bdc3c7; padding-bottom: 4px; margin-top: 32px; }}
  h3 {{ color: #34495e; }}
  .meta {{ background: #f8f9fa; border-left: 4px solid #c0392b; padding: 12px; margin-bottom: 24px; }}
  .confirmed  {{ color: #27ae60; font-weight: bold; }}
  .inferred   {{ color: #e67e22; font-weight: bold; }}
  .unconfirmed{{ color: #e74c3c; font-weight: bold; }}
  table {{ width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 12px; }}
  th {{ background: #2c3e50; color: white; padding: 8px; text-align: left; }}
  td {{ border: 1px solid #bdc3c7; padding: 6px 8px; }}
  tr:nth-child(even) {{ background: #f8f9fa; }}
  .scorecard {{ background: #2c3e50; color: white; padding: 16px; border-radius: 4px; }}
  .scorecard td {{ border-color: #5d6d7e; color: white; }}
  .pass {{ color: #2ecc71; font-weight: bold; }}
  .fail {{ color: #e74c3c; font-weight: bold; }}
  .iteration-block {{ border: 1px solid #bdc3c7; margin: 8px 0; padding: 8px; border-radius: 4px; }}
  .page-break {{ page-break-before: always; }}
  footer {{ margin-top: 40px; font-size: 10px; color: #7f8c8d; border-top: 1px solid #bdc3c7; padding-top: 8px; }}
</style>
</head>
<body>

<h1>FIND EVIL — Incident Report</h1>

<div class="meta">
  <strong>Case:</strong> {case_id}<br>
  <strong>Generated:</strong> {generated_at} UTC<br>
  <strong>Analyst:</strong> FIND EVIL Autonomous Agent<br>
  <strong>Tool:</strong> SANS SIFT Workstation + Custom MCP Server<br>
  <strong>Evidence Integrity:</strong> <span class="{integrity_class}">{integrity_status}</span>
</div>

<h2>Executive Summary</h2>
<p>{summary}</p>

<h2>Confirmed Findings</h2>
<table>
  <tr><th>Finding</th><th>Source Tool</th><th>Timestamp (UTC)</th><th>Confidence</th></tr>
  {confirmed_rows}
</table>

<h2>Inferred Findings</h2>
<table>
  <tr><th>Finding</th><th>Basis</th><th>Confidence</th></tr>
  {inferred_rows}
</table>

<h2>Unconfirmed Hypotheses</h2>
<table>
  <tr><th>Hypothesis</th><th>Gap / Reason Unconfirmed</th></tr>
  {unconfirmed_rows}
</table>

<div class="page-break"></div>

<h2>Accuracy Scorecard</h2>
<div class="scorecard">
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  {scorecard_rows}
</table>
</div>

<h2>Evidence Integrity</h2>
<p>
  Forbidden tool violations: <strong>{forbidden_violations}</strong><br>
  Untraceable findings: <strong>{untraceable}</strong><br>
  Architectural guardrails: MCP server enforced read-only — destructive commands never exposed.
</p>

<div class="page-break"></div>

<h2>Iteration Trace</h2>
<p>Shows how agent reasoning evolved across iterations. Demonstrates self-correction capability.</p>
{iteration_blocks}

<h2>Discrepancies Detected</h2>
{discrepancy_content}

<footer>
  Generated by FIND EVIL | SANS SIFT Workstation | Protocol SIFT Extension<br>
  Audit log: ./analysis/forensic_audit.log | MCP log: ./logs/mcp_audit.log
</footer>
</body>
</html>
"""


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f)


def build_finding_rows(findings: list, confidence: str) -> str:
    rows = [f for f in findings if f.get("confidence") == confidence]
    if not rows:
        return "<tr><td colspan='4'>(none)</td></tr>"
    html = ""
    for f in rows:
        css = confidence.lower()
        html += (
            f"<tr>"
            f"<td>{_esc(f.get('finding',''))}</td>"
            f"<td>{_esc(f.get('source_tool',''))}</td>"
            f"<td>{_esc(f.get('timestamp_utc',''))}</td>"
            f"<td><span class='{css}'>{confidence}</span></td>"
            f"</tr>\n"
        )
    return html


def build_iteration_blocks(iterations: list) -> str:
    html = ""
    for it in iterations:
        tools  = ", ".join(it.get("tools_called", [])) or "none"
        corrs  = it.get("corrections", [])
        fcount = len(it.get("new_findings", []))
        html += f"""
<div class="iteration-block">
  <strong>Iteration {it['iteration']} — Phase: {it['phase']}</strong><br>
  Time: {it.get('timestamp','')}&nbsp;|&nbsp;Duration: {it.get('duration_s',0):.1f}s<br>
  Tools called: {_esc(tools)}<br>
  New findings: {fcount}
  {'<br><strong>Self-corrections:</strong>' if corrs else ''}
  {''.join(f'<br>&nbsp;&nbsp;↺ {_esc(c)}' for c in corrs)}
</div>"""
    return html or "<p>(No iterations recorded)</p>"


def build_scorecard_rows(scores: dict) -> str:
    items = [
        ("Ground truth items",    scores.get("ground_truth_size", "N/A")),
        ("Agent findings",        scores.get("agent_finding_count", "N/A")),
        ("True Positives",        scores.get("true_positives", "N/A")),
        ("False Positives",       scores.get("false_positives", "N/A")),
        ("False Negatives",       scores.get("false_negatives", "N/A")),
        ("Precision",             f"{scores.get('precision',0):.1%}"),
        ("Recall",                f"{scores.get('recall',0):.1%}"),
        ("F1 Score",              f"{scores.get('f1_score',0):.4f}"),
        ("Hallucination Rate",    f"{scores.get('hallucination_rate',0):.1%}"),
    ]
    return "".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in items)


def _esc(s: str) -> str:
    return str(s).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--case",     required=True)
    parser.add_argument("--findings", default="analysis/findings.json")
    parser.add_argument("--accuracy", default="reports/accuracy_report.json")
    parser.add_argument("--output",   default="reports/incident_report.pdf")
    args = parser.parse_args()

    case_dir  = Path(args.case)
    findings  = load_json(case_dir / args.findings)
    accuracy  = load_json(case_dir / args.accuracy)
    out_path  = case_dir / args.output
    out_path.parent.mkdir(parents=True, exist_ok=True)

    all_findings = findings.get("findings", [])
    iterations   = findings.get("iterations", [])
    scores       = accuracy.get("scores", {})
    integ        = accuracy.get("evidence_integrity", {})

    # Count discrepancies (corrections across all iterations)
    all_corrections = [c for it in iterations for c in it.get("corrections", [])]

    integrity_pass   = integ.get("integrity_passed", True)
    integrity_status = "PASS — No evidence modifications detected" if integrity_pass else "FAIL — See violations below"
    integrity_class  = "pass" if integrity_pass else "fail"

    # Build summary sentence
    confirmed_count = sum(1 for f in all_findings if f.get("confidence") == "CONFIRMED")
    summary = (
        f"The autonomous agent ran {len(iterations)} analysis iteration(s) across "
        f"{len(set(it['phase'] for it in iterations))} investigation phase(s), "
        f"producing {len(all_findings)} total findings ({confirmed_count} CONFIRMED). "
        f"Evidence integrity was maintained throughout — all operations were read-only "
        f"and enforced architecturally via the custom MCP server."
    )

    # Discrepancy section
    disc_html = (
        "<ul>" + "".join(f"<li>{_esc(c)}</li>" for c in all_corrections) + "</ul>"
        if all_corrections else "<p>(No discrepancies or corrections detected)</p>"
    )

    html_content = HTML_TEMPLATE.format(
        case_id            = case_dir.name,
        generated_at       = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
        integrity_status   = integrity_status,
        integrity_class    = integrity_class,
        summary            = summary,
        confirmed_rows     = build_finding_rows(all_findings, "CONFIRMED"),
        inferred_rows      = build_finding_rows(all_findings, "INFERRED"),
        unconfirmed_rows   = build_finding_rows(all_findings, "UNCONFIRMED"),
        scorecard_rows     = build_scorecard_rows(scores),
        forbidden_violations = len(integ.get("forbidden_tool_violations", [])),
        untraceable        = integ.get("untraceable_findings", 0),
        iteration_blocks   = build_iteration_blocks(iterations),
        discrepancy_content= disc_html,
    )

    HTML(string=html_content, base_url=str(case_dir)).write_pdf(str(out_path))
    print(f"[Report] PDF written to: {out_path}")


if __name__ == "__main__":
    main()
